name: lint-and-test

on: push


jobs:
  check:
    runs-on: ubuntu-latest
    name: Check (on Python 3.11)
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - uses: actions/checkout@v3
      - uses: pre-commit/action@v3.0.0


  test:
    needs: check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py_version: [ '3.11' ]
    name: "Test (on Python ${{ matrix.py_version }})"
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py_version }}
      - name: Check out src from Git
        uses: actions/checkout@v3
      - name: Install SQL extensions
        run: |
          sudo apt-get update
          sudo apt-get -y install postgresql-client
          psql -h $PGHOST -p $PGPORT --file scripts/load-psql-extensions.sql -U $PGUSER $PGDB;
      - name: Install necessary items for netcdf
        run: |
          sudo apt-get install libhdf5-serial-dev netcdf-bin libnetcdf-dev
      - run: make test
    env:
      PGHOST: 127.0.0.1
      PGPORT: 5432
      PGUSER: flexmeasures_test
      PGDB: flexmeasures_test
      PGPASSWORD: flexmeasures_test

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:14.17 
        env:
          POSTGRES_USER: flexmeasures_test
          POSTGRES_PASSWORD: flexmeasures_test
          POSTGRES_DB: flexmeasures_test
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
